spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/productdb}
    username: ${SPRING_DATASOURCE_USERNAME:apiuser}
    password: ${SPRING_DATASOURCE_PASSWORD:apipassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization : true

server:
  port: 8080